# In order not to overlap with other applications.
server.port=9090

dou.training.set.csv.file.path=./training-set/dou/2016_may_mini.csv
dou.regression.model.directory.path=./training-set/dou/regression-model
dou.clustering.model.directory.path=./training-set/dou/clustering-model

lyrics.training.set.directory.path=./training-set/music
lyrics.model.directory.path=./training-set/music/model

# Selection from 5 possible pipelines: LogisticRegressionPipeline, NaiveBayesBagOfWordsPipeline, NaiveBayesTFIDFPipeline, RandomForestPipeline and FeedForwardNeuralNetworkPipeline
# lyrics.pipeline=LogisticRegressionPipeline
lyrics.pipeline=NaiveBayesBagOfWordsPipeline
#music.pipeline=LogisticRegressionPipeline

mnist.training.set.image.file.path=./training-set/mnist/train-images-idx3-ubyte
mnist.training.set.label.file.path=./training-set/mnist/train-labels-idx1-ubyte
mnist.test.set.image.file.path=./training-set/mnist/t10k-images-idx3-ubyte
mnist.test.set.label.file.path=./training-set/mnist/t10k-labels-idx1-ubyte

mnist.training.set.parquet.file.path=./training-set/mnist/training-set.parquet
mnist.test.set.parquet.file.path=./training-set/mnist/test-set.parquet
mnist.model.directory.path=./training-set/mnist/model
mnist.validation.set.directory.path=<should be correct path used on different environments>

#music.training.set.csv.file.path = ./training-set/music/tcc_ceds_music.csv
#music.regression.model.directory.path = ./training-set/music/regression-model
#music.model.directory.path=./training-set/music/model/
music.training.set.directory.path=./training-set/music/
music.model.directory.path=./training-set/music/model/
#music.clustering.model.directory.path = ./training-set/music/clustering-model